spring:
  application:
    name: course-tracker

  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:sbipdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa: 
    hibernate:
      ddl-auto: none
  
  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

management: 
  endpoints:
    web:
      exposure:
        include: health, info

  info:
    git:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# # Initializes schema on each execution
# spring.datasource.initialization-mode=embedded
# # Database URL
# spring.datasource.url=jdbc:h2:mem:sbipdb
# # H2 Drive class
# spring.datasource.driverClassName=org.h2.Driver
# # Database Username
# spring.datasource.username=sa
# # Database Password
# spring.datasource.password=password
# #Enable H2 console
# spring.h2.console.enabled=true
# # Spring MVC Hidden Method filter
# spring.mvc.hiddenmethod.filter.enabled=true
# # Disable the DDL generation
# spring.jpa.hibernate.ddl-auto=none

# spring.application.name=course-tracker

