spring:
  application:
    name: course-tracker
  
  profiles:
    active: testdata

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/sbip
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5

  jpa: 
    hibernate:
      ddl-auto: none
  
  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

management: 
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  
  endpoint:
    health:
      show-details: always
      show-components: always

  info:
    git:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# # Initializes schema on each execution
# spring.datasource.initialization-mode=embedded
# # Database URL
# spring.datasource.url=jdbc:h2:mem:sbipdb
# # H2 Drive class
# spring.datasource.driverClassName=org.h2.Driver
# # Database Username
# spring.datasource.username=sa
# # Database Password
# spring.datasource.password=password
# #Enable H2 console
# spring.h2.console.enabled=true
# # Spring MVC Hidden Method filter
# spring.mvc.hiddenmethod.filter.enabled=true
# # Disable the DDL generation
# spring.jpa.hibernate.ddl-auto=none

# spring.application.name=course-tracker

