apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: postgres
data:
  init.sql: |
    CREATE DATABASE sbip;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    db: postgres
spec:
  selector:
    matchLabels:
      db: postgres
  template:
    metadata:
      labels:
        db: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/bitnami/postgresql:14
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "true"
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    db: postgres
spec:
  type: ClusterIP
  selector:
    db: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

